
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: emotwo
    password: ${password}
#    url: jdbc:mysql://123.59.72.69:3306/emucoo-2.0?useUnicode=true&characterEncoding=utf-8&useSSL=true&autoReconnect=true&allowMultiQueries=true
    url: jdbc:mysql://192.168.16.173:3306/emucoo-cfb?useUnicode=true&characterEncoding=utf-8&useSSL=true&autoReconnect=true&allowMultiQueries=true
  redis:
    database: 1
    cluster:
      nodes: 192.168.16.179:7000,192.168.16.179:7001,192.168.16.179:7002,199.168.16.180:7001,192.168.16.180:7002,192.168.16.180:7003

publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJ8hIQck8O61Ev0F8C3YLQv6qwhZ7G4oMy53jwwiL/8L2n3aEHRtUySJlRDSV891M7+IksolgtHoyou9LaIJP9sCAwEAAQ==
password: gh9C+z6OhPoMFfBm0/oZXhidM9a5NBDIcqIgEXV4EH2pO8chIOEnJjMlrAb7uvlJHyUfwlrp2J+jjiEqylDAtw==

logging:
  config: classpath:logback-base.xml
  path: logs


